listen              1935;
max_connections     1000;
daemon              off;
srs_log_tank        console;

http_server {
    enabled         on;
    listen          8080;
}

http_api {
    enabled         on;
    listen          1985;
}

stats {
    network         0;
}

vhost __defaultVhost__ {
    hls {
        enabled         on;
        hls_fragment    2;
        hls_window      10;
        hls_cleanup     on;
        hls_dispose     30;
        hls_wait_keyframe on;
        hls_use_fmp4    on;
    }

    http_hooks {
        enabled         on;
        on_publish      http://host.docker.internal:3003/api/srs/callbacks/on-publish;
        on_unpublish    http://host.docker.internal:3003/api/srs/callbacks/on-unpublish;
        on_play         http://host.docker.internal:3003/api/srs/callbacks/on-play;
        on_stop         http://host.docker.internal:3003/api/srs/callbacks/on-stop;
        on_hls          http://host.docker.internal:3003/api/srs/callbacks/on-hls;
        on_dvr          http://host.docker.internal:3003/api/srs/callbacks/on-dvr;
    }

    rtc {
        enabled     on;
        rtmp_to_rtc on;
    }
}
